roles/dspace: Disable Java assistive technologies
There is apparently a bug in Debian and Ubuntu's OpenJDK package
that causes some libraries like JFreeChart to fail to load when
using a headless JRE. In our case the Atmire CUA Usage Statistics
graphs are blank and there is an error like this printed in the
DSpace log:

2020-01-12 05:00:10,163 ERROR org.dspace.app.xmlui.cocoon.DSpaceCocoonServletFilter @ Serious Error Occurred Processing Request!
org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart

The library exists, but cannot be loaded. I see this error has
been occurring for months and nobody told me! I don't understand
it, but commenting out the assistive technologies does fix it.

See: https://code-maven.com/slides/jenkins-intro/no-graph-error
See: https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror
See: https://github.com/microsoft/vscode-arduino/issues/644
See: https://github.com/airsonic/airsonic/issues/353