roles/common: fix bytes error in backup_mysql.py
sb.run() was returning bytes for stderr, which results in this error
message:

    TypeError: Object of type bytes is not JSON serializable

We need to decode() the bytes to string first.